version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
      
    commands:
      - echo "Installing .NET Core SDK..."
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel LTS
      - export PATH="$PATH:$HOME/.dotnet"
      - dotnet publish -c Release -o ./publish

  pre_build:
    commands:
      - echo "Restoring dotnet"
      - dotnet restore

  build:
    commands:
      - echo "Building the .NET application"
      - dotnet build

  post_build:
    commands:
      - echo "Running unit tests"
      - dotnet test
artifacts:
  files:
    - './**/*'
